on: [push]
name: Toot, together!
jobs:
  toot:
    name: Toot
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: actions/checkout@v2
      - name: Toot
        uses: joschi/toot-together@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          MASTODON_URL: https://social.linux.pizza
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
